# Default settings can be fine. But if we want customizations,
# can have properties here.
graphql:
      servlet:
               mapping: /graphql
               enabled: true
               corsEnabled: false